name = "pairsum-leap"
compatibility_date = "2023-10-30"

workers_dev = false
kv_namespaces = [
    { binding = "KV", id = "test" }
]

[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "test"
